### ISSUE TITLE
faq for villager rm detection

### ISSUE THREAD

**Issue by Godlander** [MinecraftCommands/commanderbot#8]
villager for right mouse detection:
`summon villager ~ ~ ~ {Silent:1b,NoAI:1b,Offers:{}}`
simple summon command for a villager that doesnt move, make sound, or have trades

invisible villager for left and right mouse detection:
`summon villager ~ ~ ~ {Silent:1b,NoAI:1b,ActiveEffects:[{Id:6b,Amplifier:5b,Duration:1000000,ShowParticles:0b},{Id:14b,Amplifier:0b,Duration:1000000,ShowParticles:0b}],Offers:{}}`
summons a villager with invisibility and instant health on top of the previous command.

godlander's input stack (probably dont need to actualy add this one):
`summon armor_stand ~ ~ ~ {UUIDMost:0,UUIDLeast:1,Invulnerable:1b,Glowing:1b,Small:1b,Passengers:[{id:"minecraft:minecart",Invulnerable:1b},{id:"minecraft:villager",NoAI:1b,NoGravity:1b,Silent:1b,ActiveEffects:[{Id:6b,Amplifier:5b,Duration:1000000,ShowParticles:0b},{Id:14b,Amplifier:0b,Duration:1000000,ShowParticles:0b}],Offers:{}}]}`
just the summon command i use to make this stack
![image](https://user-images.githubusercontent.com/16228717/57001165-20a78400-6b6c-11e9-8046-24e13c61fc34.png)
allows many input grabs from minecart and villager and can show a shader with `Glowing:1b` on the armorstand.

**Comment by Arcensoth** [comment]
If you post a message version of this to #resources I can link it in the FAQ entry.
